var GAME_LEVELS = [
  ["                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              t           x                                             ",
   "                                          t                               xxxxxxxxxxxxxx",
   "  x                                                                       xx           x",
   "  x                                                                       x            x",
   "  x                   o                                                   x            x",
   "  x                                                                       x            x",
   "  x                                       o                                            x",
   "  x           o             xxx         xxxxx              o                    o      x",
   "  x           xxxx                                        xxx       x                  x",
   "  x  @     o  xxxx           o                      ox           q  x     x     8     xx",
   "  xxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxx!!!!!xxxxxxxx   x                  x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x                  x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x                  x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                        ",
   "                                                                                        "],
  ["                                                           x!x                                                       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x                      x       ",
   " x                                                                       xxx                                 x       ",
   " x                 o                                                  xxxx xxx                               x       ",
   " x                xxx                                                 xtt ttxx                               x       ",
   " x                                                                                                           x       ",
   " x                                                                                                           x       ",
   " x                                                                                                           x       ",
   " x                        xx!xxxxx                                                     o           8         x       ",
   " x         xx!xx                             xxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x       ",
   " x                                               v                     b   3                                 x       ",
   " xo                                                                                                    q  xxxx       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                 x       ",
   " x                         x                                                                                 x       ",
   " x                         x 8                                                                            8  x       ",
   " x                      s  xxxxxxxxxxxxxxxx!!xxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   x       ",
   " x          xxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxv                                      x       ",
   " x          ttt        tttt                                                                        xxxx      x       ",
   " x                                                                                                          ox       ",
   " x                                                                                                        xxxx       ",
   " x   @            o                   x     o    8        x                                            8  xxxx       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                      xxxxx                                          ",
   "                                                                                                                     "],
  ["                                                                                                                        x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "                                                                                                                        x",
   "                                                                                                                        x",
   "                                      o                                                                                 x",
   "                                                                                                                        x",
   "                                                           xxx                                                          x",
   "   8                                                                                                                    x",
   "                                                                                                                        x",
   "                                               xxx                  o                                                   x",
   "                                                                     xx                                          8      x",
   "                                                                                                                        x",
   "                                           8                                                                            x",
   "                                                           xxxx                                                         x",
   "                                                           xxxx             o                                           x",
   "               8                                                           xxx                                          x",
   "                                                                                                                        x",
   "                                                                                                                   q    x",
   "                                                                                           o                            x",
   "                                                                                          xxx                           x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                            o            o                                                           x",
   "  x                        3                  xxxxx       xxxx         o                       xxxxxxx                  x",
   "  x   x                                                            8  xxxx                                              x",
   "  x                                                                                                                     x",
   "  x                                                                                    xxxxxxxxx                        x",
   "  x                                   o                                                    q   x                        x",
   "  x                                  xxxx                                                                               x",
   "  x                                                                                                                     x",
   "  x 8                                                                                                                   x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                       q             x",
   "  x                             o                                                                                       x",
   "  x                           xxxx                                                                                      x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                     o                                                                               q               x",
   "  x                   xxxx                                                                                              x",
   "  x                                                                                                                     x",
   "  x                                                       8                                                  x          x",
   "  x                                                                                                                     x",
   "  x                                                                                                                     x",
   "  x                o                                                                                                    x",
   "  x           xxxxxxxxxx!!!!!!!!!!!!!!!!xxx!!!xx!!!!xx!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  x                                         v    v     v       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                            !!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                         q  xxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                                      xx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   @    o                  xx!!xx8                                   jxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                         ",
   "                                                                                                                         "],
  ["                                                                                                              x",
   "                                                                     o                                        x",
   "                                                                    xxx                         q             x",
   "                                                                     t                                        x",
   "                                                                                                              x",
   "                                                          o                                       q           x",
   "                                                         xxx                                                  x",
   "                                                      3                                                       x",
   "                                                                                                              x",
   "                                                 o                                                            x",
   "                                                xx                                          8                 x",
   "                                                                                                              x",
   "                                                                                                              x",
   "                                                         o                                                    x",
   "                                                        xxx           o                                       x",
   "                                                                      xx                                      x",
   "     3                                                                 b                                      x",
   "                                                                                  o                           x",
   "                       xxx                          xxx                           xx               o          x",
   "                        v                            v                             t               xx         x",
   "                                                                                                    t         x",
   "                                                                                         x                    x",
   "                                                                                         t                    x",
   "                                                                                                              x",
   "                                                                                                              x",
   "x     @     s    o                         q   xxx    =   x      o           8                    b         j x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    " x     x    xxxxxx   x    x                                                                                   x",
    " x     x    x    x   x    x                                                                                   x",
    "  xxxxx     x    x   x    x                                                                                   x",
    "    x       xxxxxx   xxxxxx                                                                                   x",
    "    x                                                                                                         x",
    "                                                                                                              x",
    " x     x   x    xx     x                                                                                      x",
    " x     x   x    x x    x                                                                                      x",
    " x  x  x   x    x  x   x                                                                                      x",
    " x x x x   x    x   x  x                                                                                      x",
    " x     x   x    x    xxx                                                                                      x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "                                                                                                              x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                                              "]



];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
